# Generated by Django 5.2.5 on 2025-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If checked, video will be visible on the site'),
        ),
    ]
