# Generated by Django 5.2.5 on 2025-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional category image', null=True, upload_to='categories/'),
        ),
    ]
