# Generated by Django 5.2.5 on 2025-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cms_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Name of the site (e.g., Desi X Zone, xHamster)', max_length=100)),
                ('title', models.CharField(help_text='Modal title', max_length=200)),
                ('content', models.TextField(help_text='Modal content (HTML allowed)')),
                ('confirm_text', models.CharField(default='I am 18 or older', help_text='Text for confirm button', max_length=100)),
                ('deny_text', models.CharField(default='I am under 18', help_text='Text for deny button', max_length=100)),
                ('deny_redirect_url', models.URLField(default='https://www.google.com', help_text='URL to redirect to when user denies age')),
                ('is_active', models.BooleanField(default=True, help_text='Show this modal on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Age Verification',
                'verbose_name_plural': 'Age Verification',
            },
        ),
    ]
