# Generated by Django 5.2.5 on 2025-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_email_verification_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageverification',
            name='site_name',
            field=models.CharField(help_text='Name of the site (e.g., Adulto, xHamster)', max_length=100),
        ),
    ]
