# Generated by Django 5.2.5 on 2025-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule video to be published at this time', null=True),
        ),
    ]
