# Generated by Django 5.2.5 on 2025-10-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
    ]
