# Generated by Django 5.2.5 on 2025-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_video_seo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('header-top-banner', 'Header Top Banner'), ('footer-top-banner', 'Footer Top Banner'), ('global-popunder-desktop', 'Global Popunder (Desktop)'), ('global-popunder-mobile', 'Global Popunder (Mobile)'), ('global-interstitial-desktop', 'Global Interstitial (Desktop)'), ('global-interstitial-mobile', 'Global Interstitial (Mobile)'), ('global-instant-message', 'Global Instant Message (Chat Box)'), ('global-sticky-banner', 'Global Sticky Banner'), ('home-top-banner', 'Home Top Banner'), ('home-sidebar-top', 'Home Sidebar Top'), ('home-sidebar-bottom', 'Home Sidebar Bottom'), ('home-incontent-1', 'Home In-Content 1'), ('home-incontent-2', 'Home In-Content 2'), ('home-recommendation-1', 'Home Recommendation Widget'), ('home-bottom-banner', 'Home Bottom Banner'), ('video-top-banner', 'Video Top Banner'), ('video-instream', 'Video In-Stream'), ('video-below-player', 'Video Below Player'), ('video-sidebar-top', 'Video Sidebar Top'), ('video-sidebar-bottom', 'Video Sidebar Bottom'), ('video-info-comments', 'Video Info-Comments Banner'), ('video-slider', 'Video Slider'), ('video-after-related', 'Video After Related Videos'), ('video-outstream', 'Video Outstream'), ('videos-top-banner', 'Videos Top Banner'), ('videos-sidebar-top', 'Videos Sidebar Top'), ('videos-sidebar-bottom', 'Videos Sidebar Bottom'), ('videos-incontent-1', 'Videos In-Content 1'), ('videos-incontent-2', 'Videos In-Content 2'), ('videos-recommendation-1', 'Videos Recommendation Widget'), ('search-top-banner', 'Search Top Banner'), ('search-incontent-1', 'Search In-Content 1'), ('search-incontent-2', 'Search In-Content 2'), ('search-bottom-banner', 'Search Bottom Banner'), ('popular-top-banner', 'Popular Top Banner'), ('popular-middle-banner', 'Popular Middle Banner'), ('popular-incontent-1', 'Popular In-Content 1'), ('popular-incontent-2', 'Popular In-Content 2'), ('categories-top-banner', 'Categories Top Banner'), ('categories-middle-banner', 'Categories Middle Banner'), ('categories-bottom-banner', 'Categories Bottom Banner')], help_text='Select the ad placement location. Each location can have only one ad.', max_length=50, unique=True)),
                ('script', models.TextField(help_text='HTML/JavaScript ad script content')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this ad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['ad_type'],
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(help_text="Setting key (e.g., 'site_title', 'contact_email', 'meta_verification_script')", max_length=100, unique=True),
        ),
    ]
