# Generated by Django 5.2.5 on 2025-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ad_alter_settings_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('header-top-banner', 'Header Top Banner'), ('global-popunder-desktop', 'Global Popunder (Desktop)'), ('global-popunder-mobile', 'Global Popunder (Mobile)'), ('global-interstitial-desktop', 'Global Interstitial (Desktop)'), ('global-interstitial-mobile', 'Global Interstitial (Mobile)'), ('global-instant-message', 'Global Instant Message (Chat Box)'), ('global-sticky-banner', 'Global Sticky Banner'), ('home-sidebar-top', 'Home Sidebar Top'), ('home-incontent-1', 'Home In-Content 1'), ('home-bottom-banner', 'Home Bottom Banner (Leaderboard)'), ('video-below-player', 'Video Below Player'), ('video-sidebar-top', 'Video Sidebar Top'), ('videos-sidebar-top', 'Videos Sidebar Top'), ('videos-incontent-1', 'Videos In-Content 1'), ('search-incontent-1', 'Search In-Content 1'), ('popular-middle-banner', 'Popular Middle Banner (Leaderboard)'), ('categories-middle-banner', 'Categories Middle Banner (Leaderboard)')], help_text='Select the ad placement location. Each location can have only one ad.', max_length=50, unique=True),
        ),
    ]
