# Generated by Django 5.2.5 on 2025-11-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ad_ad_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['placement', 'ad_type'], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AddField(
            model_name='ad',
            name='placement',
            field=models.CharField(choices=[('header-top', 'Header Top'), ('footer-top', 'Footer Top'), ('global-popunder-desktop', 'Global Popunder (Desktop)'), ('global-popunder-mobile', 'Global Popunder (Mobile)'), ('global-interstitial-desktop', 'Global Interstitial (Desktop)'), ('global-interstitial-mobile', 'Global Interstitial (Mobile)'), ('global-instant-message', 'Global Instant Message'), ('global-sticky-banner', 'Global Sticky Banner'), ('home-top', 'Home Top'), ('home-sidebar', 'Home Sidebar'), ('home-incontent', 'Home In-Content'), ('home-bottom', 'Home Bottom'), ('video-below-player', 'Video Below Player'), ('video-sidebar', 'Video Sidebar'), ('videos-sidebar', 'Videos Sidebar'), ('videos-incontent', 'Videos In-Content'), ('search-incontent', 'Search In-Content'), ('popular-middle', 'Popular Middle'), ('categories-middle', 'Categories Middle')], default='home', help_text='Select the ad placement location', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('sticky-banner', 'Sticky Banner'), ('fullpage-interstitial', 'Fullpage Interstitial'), ('instream-video', 'In-Stream Video'), ('video-slider', 'Video Slider'), ('recommendation-widget', 'Recommendation Widget'), ('multi-format', 'Multi-Format'), ('inpage-push-notifications', 'In-Page Push Notifications')], help_text='Select the ad format type (banner, sticky-banner, etc.)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('placement', 'ad_type')},
        ),
    ]
