# Generated by Django 5.2.5 on 2025-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ad_options_ad_placement_alter_ad_ad_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['ad_type'], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('sticky-banner', 'Sticky Banner'), ('fullpage-interstitial', 'Fullpage Interstitial'), ('instream-video', 'In-Stream Video'), ('video-slider', 'Video Slider'), ('recommendation-widget', 'Recommendation Widget'), ('multi-format', 'Multi-Format'), ('inpage-push-notifications', 'In-Page Push Notifications')], help_text='Select the ad format type (banner, sticky-banner, etc.). Only 8 ads total - one per format.', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='ad',
            name='placement',
        ),
    ]
