# Generated by Django 5.2.5 on 2025-11-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ad_options_alter_ad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['placement', 'ad_type'], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AddField(
            model_name='ad',
            name='placement',
            field=models.CharField(choices=[('header-top', 'Header Top Banner (728x90 Desktop, 320x50 Mobile)'), ('global-sticky-bottom', 'Global Sticky Banner Bottom (728x90 Desktop, 320x50 Mobile)'), ('global-popunder-desktop', 'Global Popunder Desktop (Full Page)'), ('global-popunder-mobile', 'Global Popunder Mobile (Full Page)'), ('global-interstitial', 'Global Interstitial (Full Screen Desktop/Mobile)'), ('global-instant-message', 'Global Instant Message Chat (300x250 Desktop, 280x250 Mobile)'), ('global-inpage-push', 'Global In-Page Push Notification (Responsive, Configurable Position)'), ('incontent', 'In-Content Banner (728x90 Desktop, Full Width Mobile) - Home/Videos/Search'), ('sidebar', 'Sidebar Rectangle (300x250 Desktop, Full Width Mobile) - All Pages with Sidebar'), ('home-bottom', 'Home Bottom Leaderboard (970x250 Desktop, 728x90 Mobile)'), ('video-below-player', 'Video Below Player Banner (728x90 Desktop, 320x50 Mobile)'), ('video-instream', 'Video In-Stream VAST (VAST URL for instream-video ad_type)'), ('video-slider', 'Video Slider (VAST URL, slides from right bottom)')], default='header-top', help_text='Select the ad placement location', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('sticky-banner', 'Sticky Banner'), ('fullpage-interstitial', 'Fullpage Interstitial'), ('instream-video', 'In-Stream Video'), ('video-slider', 'Video Slider'), ('recommendation-widget', 'Recommendation Widget'), ('multi-format', 'Multi-Format'), ('inpage-push-notifications', 'In-Page Push Notifications')], help_text='Select the ad format type (banner, sticky-banner, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='script',
            field=models.TextField(help_text='HTML/JavaScript ad script content (or VAST URL for instream-video/video-slider)'),
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('placement', 'ad_type')},
        ),
    ]
