# Generated by Django 5.2.5 on 2026-01-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_ad_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMCAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Reporter's name", max_length=150)),
                ('email', models.EmailField(help_text="Reporter's email address", max_length=254)),
                ('message', models.TextField(help_text='Report message/details')),
                ('page_url', models.URLField(blank=True, help_text='URL of the page where report was submitted', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', help_text='Report status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dmca_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMCA Report',
                'verbose_name_plural': 'DMCA Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
