# Generated by Django 5.2.5 on 2026-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dmcareport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_active', '-created_at'], name='core_video_is_acti_7b12ff_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_active', '-views'], name='core_video_is_acti_868064_idx'),
        ),
    ]
