# Generated by Django 5.2.5 on 2026-03-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='core_video_is_acti_7b12ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='core_video_is_acti_868064_idx',
        ),
    ]
